[package]
name = "actix_web_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
mime = "0.3.17"
tokio = { version = "1.27.0", features = ["full"] }
